"""Create plagiarism tables

Revision ID: 11c6713d0de7
Revises: 
Create Date: 2025-08-25 20:53:34.379586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c6713d0de7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_matches', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('sentence_matches', sa.Column('bounding_boxes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentence_matches', 'bounding_boxes')
    op.drop_column('sentence_matches', 'page_number')
    # ### end Alembic commands ###
